name: WereWolfPlugin
version: "1.9"
api-version: "1.13"
author: Ph1Lou
main: fr.ph1lou.werewolfplugin.Main
load: STARTUP
commands:

  ww:
    description: player commands
  a:
    description: admin commands


